### ISSUE TITLE
Please fix the Travis CI build error

### ISSUE THREAD

**Issue by hsluoyz** [casbin-rs/sqlx-adapter#14]
![image](https://user-images.githubusercontent.com/3787410/80930351-a72d1c00-8de5-11ea-90f2-79ab85d558ac.png)

@hackerchai @GopherJ

**Comment by hackerchai** [comment]
> ![image](https://user-images.githubusercontent.com/3787410/80930351-a72d1c00-8de5-11ea-90f2-79ab85d558ac.png)
> 
> @hackerchai @GopherJ 

I will take this.

**Comment by 0x8f701** [comment]
seems solved in: #16

**Comment by hackerchai** [comment]
@hsluoyz already sloved in #16

**Comment by hsluoyz** [comment]
Looks good, except so many commits..

**Comment by hackerchai** [comment]
> Looks good, except so many commits..

An experimental change on CI, so it needs lots of debug. I will avoid this next time.
