### ISSUE TITLE
Dynamic sqlx compile support

### ISSUE THREAD

**Issue by hackerchai** [casbin-rs/sqlx-adapter#18]
When we use CI/CD, we have to set up database and create tables in order to build the adapter. Also when developers use sqlx-adapter, they don't need to verify the SQL syntax. I think we should add dynamic compile feature to avoid compile-time SQL verify.

**Comment by hackerchai** [comment]
@GopherJ @xcaptain  see https://github.com/launchbadge/sqlx/issues/60
There is a WIP feature which support disabling query typechecking. Maybe we can use this  rather than writing proc-macro.

**Comment by hackerchai** [comment]
see #39

**Comment by hackerchai** [comment]
@hsluoyz Already solved. See #39

**Comment by hsluoyz** [comment]
OK.
