### ISSUE TITLE
More efficient `load_filtered_policy`

### ISSUE THREAD

**Issue by bodymindarts** [casbin-rs/sqlx-adapter#30]
When working with a large policy it makes sense only to load a subset of policies to make the enforcement decision.

This adapter unfortunately loads all the rules and [filters them in memory](https://github.com/casbin-rs/sqlx-adapter/blob/master/src/adapter.rs#L171).

Would you accept a PR that moves the filter / selection logic into an SQL query for performance / efficiency?

**Comment by hsluoyz** [comment]
@bodymindarts it's a good idea. Go ahead with a PR please!

**Comment by hsluoyz** [comment]
@GopherJ @hackerchai @PsiACE please watch all repos under https://github.com/casbin-rs/ so you can get notified at the first time about issues and PRs.

**Comment by bodymindarts** [comment]
Reopened after rebase: https://github.com/casbin-rs/sqlx-adapter/pull/35

**Comment by bodymindarts** [comment]
Pr is still open https://github.com/casbin-rs/sqlx-adapter/pull/35
