### ISSUE TITLE
Need changelog for every release

### ISSUE THREAD

**Issue by hsluoyz** [casbin-rs/sqlx-adapter#32]
@GopherJ @hackerchai @PsiACE , currently, for several repos, it's very hard to know what features and bugs have been added/resolved in each release:

https://github.com/casbin-rs/sqlx-adapter/releases
https://github.com/casbin-rs/actix-casbin/releases
https://github.com/casbin-rs/diesel-adapter/releases
https://github.com/casbin-rs/actix-casbin-auth/releases

The Releases page all contain useless information like Release x.y.z, bump to x.y.z, merge PR, etc. This is not friendly for our users as they can gain nothing from the changelog. I hope we can have some sort of changelog that shows what have been done in each release.

![image](https://user-images.githubusercontent.com/3787410/88469197-51b66600-cf21-11ea-9789-7de9d523672b.png)

**Comment by hsluoyz** [comment]
I think semantic-release can help on it. See how Node-Casbin do it.

**Comment by PsiACE** [comment]
The workflow of semantic release does not have a good integration scheme for the time being, but we can find some great tools to generate change logs. I will deal with this problem.

**Comment by hsluoyz** [comment]
You mean it doesn't support Rust?

**Comment by 0x8f701** [comment]
I believe this changelog is caused by un-squashed commit? I need find a good way to integrate  semantic-release because it'll not update version number in `Cargo.toml`

**Comment by hsluoyz** [comment]
Casbin-RS is using Semantic-release: https://github.com/casbin/casbin-rs/pull/153

Configuring it for other repos requires non-trivial efforts. So close it here for now.
