### ISSUE TITLE
sqlx changed features names

### ISSUE THREAD

**Issue by simoneromano96** [casbin-rs/sqlx-adapter#42]
Hello, sqlx just changed the feature names from `runtime-tokio` and `runtime-async-std` to `runtime-{rt}-{tls}` where rt is `tokio`, `actix` or `async-std` and tls is `native-tls` or `rustls`.

This is currently breaking the compilation on some of my projects, should I open a PR?

**Comment by simoneromano96** [comment]
This is the compilation error:
```sh
error: the features 'runtime-actix', 'runtime-async-std' and 'runtime-tokio' have been removed in
     favor of new features 'runtime-{rt}-{tls}' where rt is one of 'actix', 'async-std' and 'tokio'
     and 'tls' is one of 'native-tls' and 'rustls'.
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-0.4.1/src/lib.rs:8:1
   |
8  | / compile_error!(
9  | |     "the features 'runtime-actix', 'runtime-async-std' and 'runtime-tokio' have been removed in
10 | |      favor of new features 'runtime-{rt}-{tls}' where rt is one of 'actix', 'async-std' and 'tokio'
11 | |      and 'tls' is one of 'native-tls' and 'rustls'."
12 | | );
   | |__^

error: aborting due to previous error

error: could not compile `sqlx`
```

**Comment by hackerchai** [comment]
@simoneromano96  I am working on this sqlx version bump.

**Comment by hsluoyz** [comment]
@simoneromano96 can you make a PR?

**Comment by simoneromano96** [comment]
> @simoneromano96 can you make a PR?

I'll work on it!

**Comment by hsluoyz** [comment]
@simoneromano96 @hackerchai do we need to make a new release at crates.io ?

**Comment by simoneromano96** [comment]
> 
> 
> @simoneromano96 @hackerchai do we need to make a new release at crates.io ?

I think so, also there is still the problem with localhost/127.0.0.1 on mysql 8 and rustls, I think we should write it somewhere on the readme. ( this one: https://github.com/launchbadge/sqlx/issues/846 ).

Also, SQLx master has tokio 1.0 so when they make a new release we should upgrade again the deps.

**Comment by hsluoyz** [comment]
@hackerchai plz make a new release.
