### ISSUE TITLE
rename unique constraint name

### ISSUE THREAD

**Issue by 0x8f701** [casbin-rs/sqlx-adapter#6]
It seems sometimes diesel-adapter and sqlx-adapter can have problem of duplicated constraint name,

https://github.com/casbin-rs/sqlx-adapter/blob/b8739844129df6286f4d808a572140e8b4c3491c/src/actions.rs#L26

I'll rename `unique_key` to `unique_key_diesel_adapter`, could you rename `unique_key` to `unique_key_sqlx_adapter`?

**Comment by hackerchai** [comment]
Ger it. I will fix in next push

**Comment by 0x8f701** [comment]
Seems this error is more because in diesel-adapter has two async tests which execute at the same time

But yes this can be renamed
