### ISSUE TITLE
Use with existing connection pool

### ISSUE THREAD

**Issue by mkpankov** [casbin-rs/sqlx-adapter#60]
We're using `sqlx` with Postgres using `PgPool`.

It would be good if we could pass the pool to the `SqlxAdapter` instead of it initiating a new connection by itself.

**Comment by hsluoyz** [comment]
@RobotHuang

/cc @hackerchai

**Comment by hackerchai** [comment]
> We're using `sqlx` with Postgres using `PgPool`.
> 
> It would be good if we could pass the pool to the `SqlxAdapter` instead of it initiating a new connection by itself.

@mkpankov  Good idea. We are adding this into next our todo list

**Comment by uran0sH** [comment]
I’m trying to do this.
