### ISSUE TITLE
RbacApi::delete_user() does not remove grouping policy

### ISSUE THREAD

**Issue by bk138** [casbin-rs/sqlx-adapter#64]
While adding a role to a user and then deleting the user works when using FileAdapter, it fails when using sqlx-adapter.  I've prepared a [minimal sample project here](https://github.com/bk138/casbinerr) that shows the issue.

# Steps to repro
* Assign a role to a user via add_role_for_user()
* Call delete_user()

# Expected outcome
* 'g' policy is deleted, see https://github.com/casbin/casbin-rs/blob/master/src/rbac_api.rs#L478

# Actual outcome
* 'g' policy is deleted when using FileAdapter, but not when using sqlx-adapter

# Related 
There was a similar issue for node-casbin: https://github.com/casbin/node-casbin/issues/118

**Comment by hackerchai** [comment]
> While adding a role to a user and then deleting the user works when using FileAdapter, it fails when using sqlx-adapter.  I've prepared a [minimal sample project here](https://github.com/bk138/casbinerr) that shows the issue.
> 
> 
> 
> # Steps to repro
> 
> * Assign a role to a user via add_role_for_user()
> 
> * Call delete_user()
> 
> 
> 
> # Expected outcome
> 
> * 'g' policy is deleted, see https://github.com/casbin/casbin-rs/blob/master/src/rbac_api.rs#L478
> 
> 
> 
> # Actual outcome
> 
> * 'g' policy is deleted when using FileAdapter, but not when using sqlx-adapter
> 
> 
> 
> # Related 
> 
> There was a similar issue for node-casbin: https://github.com/casbin/node-casbin/issues/118

We are working on this

**Comment by hsluoyz** [comment]
@PsiACE @GopherJ
