### ISSUE TITLE
RbacApi::delete_permissions_for_user seems to be no-op

### ISSUE THREAD

**Issue by andoriyu** [casbin-rs/sqlx-adapter#66]
Always returns `false` and sqlx shows zero queries made in database. Permissions don't get deleted.

`RbacApi::delete_permission_for_user` does work as expected.

Crate versions:

```
casbin = "2.0.9"
sqlx-adapter = { version = "0.4.2", default-features = false, features = ["runtime-tokio-native-tls", "sqlite"] }
```

**Comment by andoriyu** [comment]
Using debugger, I narrowed down the issue to [this](https://github.com/casbin-rs/sqlx-adapter/blob/master/src/adapter.rs#L247-L259) area of the code:

```
    async fn remove_filtered_policy(
        &mut self,
        _sec: &str,
        pt: &str,
        field_index: usize,
        field_values: Vec<String>,
    ) -> Result<bool> {
        if field_index <= 5 && !field_values.is_empty() && field_values.len() >= 6 - field_index {
            adapter::remove_filtered_policy(&self.pool, pt, field_index, field_values).await
        } else {
            Ok(false)
        }
    }
```

`field_values.len()` is 0, so it short circuits to `Ok(false)` branch.

**Comment by hsluoyz** [comment]
@PsiACE

**Comment by andoriyu** [comment]
I think a way to fix it is to change `adapter::remove_filtered_policy` to accept vectors of any length and change query based on length.

**Comment by hsluoyz** [comment]
@andoriyu can you make a PR?

**Comment by andoriyu** [comment]
> @andoriyu can you make a PR?

@hsluoyz sure I will try to put it together later today (PDT).

Would you be open if I change `casbin-rs` API a bit? (not in this PR)

Right now, `Rule` is `Vec<String>`. I can make polymorphic and accept things like: `[String; N]`, tuples with up to 6 values etc.

**Comment by hsluoyz** [comment]
@andoriyu we should not introduce breaking change. But we can add appropriate new APIs.

**Comment by andoriyu** [comment]
@hsluoyz the I was thinking doing would keep backward compatibility, just in addition to `Vec<String>` in will take other things.

**Comment by hsluoyz** [comment]
@andoriyu no breaking change then OK!
