### ISSUE TITLE
add support for AnyPool

### ISSUE THREAD

**Issue by prabirshrestha** [casbin-rs/sqlx-adapter#77]
Add support for `AnyPool` such that database can be chosen at runtime. `match` can then be used to run specific queries.

```rust
match pool.any_kind() {
    AnyKind::Postgres => {...},
    AnyKind::Sqlite => {...},
    AnyKind::MySql => {...},
}
```

**Comment by hsluoyz** [comment]
@prabirshrestha can you make a PR?

**Comment by prabirshrestha** [comment]
In the meantime I have file an issue on Sqlx side for making it easy to convert to and from AnyPool. https://github.com/launchbadge/sqlx/issues/2162. This could help every other projects.

**Comment by hsluoyz** [comment]
@prabirshrestha can you provide more details about this requirement?
