### ISSUE TITLE
[bug] fix CI error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects

### ISSUE THREAD

**Issue by hsluoyz** [casbin-rs/sqlx-adapter#81]
See: https://github.com/casbin-rs/sqlx-adapter/actions/runs/5461325339/jobs/9939203560

Log:

```
Run brew update
error: Could not read 050b5490e7bb098f70f3de925431a24622f2d64c
fatal: revision walk setup failed
error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects

Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
```
![image](https://github.com/casbin-rs/sqlx-adapter/assets/3787410/ef4640c8-55b7-4b11-b480-d2fd69c73a21)

**Comment by hsluoyz** [comment]
@ip1981 can you help resolve this issue first?

**Comment by ip1981** [comment]
> @ip1981 can you help resolve this issue first?

No.
