### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by smart--petea** [casbin-rs/sqlx-adapter#85]
1. the casbin 2.1.0 is not supported by the adapter of version=0.4.2
2. the sqlx is outdated. the supported version is 0.6. the actual version is 0.7.3

**Comment by hsluoyz** [comment]
@smart--petea hi, can you make a PR to support it?

**Comment by smart--petea** [comment]
related to casbin: https://github.com/casbin-rs/sqlx-adapter/pull/86
There is already a pull request regarding sqlx 0.7.
