### ISSUE TITLE
Please bump `sqlx` to `0.8`

### ISSUE THREAD

**Issue by metatoaster** [casbin-rs/sqlx-adapter#96]
This would allow projects that depend on the latest version of `sqlx` to make use of this crate, as `sqlx-sqlite` has been bumped to depend on a version of `libsqlite3-sys` incompatible with `sqlx-0.7`, which this crate directly requires through its dependency on `sqlx-0.7`.

**Comment by hsluoyz** [comment]
@metatoaster can you make a PR to fix it?
